# Generated by Django 4.2 on 2023-04-23 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Team',
        ),
    ]
