# Generated by Django 4.2 on 2023-04-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='created_at',
            new_name='participation_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='updated_at',
        ),
    ]
